# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true

# Disable caching
org.gradle.unsafe.configuration-cache=false
org.gradle.caching=false
android.enableBuildCache=false

# Enable BuildConfig for all libraries (AGP 8.x requirement)
android.defaults.buildfeatures.buildconfig=true

android.useAndroidX=true
android.enableJetifier=true

# ADD THIS: Suppress unsupported SDK warnings
android.suppressUnsupportedCompileSdk=34

FLIPPER_VERSION=0.182.0
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=false
hermesEnabled=true